symbolPreset: nerd
theme:
  dark: titanium
  light: light
setupVersion: 1
modelRoles:
  default: opencode-go/kimi-k2.7-code
  plan: opencode-go/kimi-k2.7-code
  advisor: opencode-go/minimax-m3

# plan:
#   defaultOnStartup: true
#   enabled: true

agent:
  advisor: true
task:
  disabledAgents: []
defaultThinkingLevel: auto
