symbolPreset: nerd
theme:
  dark: titanium
  light: light
setupVersion: 1
modelRoles:
  default: opencode-go/deepseek-v4-pro:xhigh
  plan: opencode-go/deepseek-v4-pro
  slow: opencode-go/deepseek-v4-pro:xhigh
task:
  disabledAgents: []
defaultThinkingLevel: auto
