symbolPreset: nerd
theme:
  dark: titanium
  light: light
setupVersion: 1
modelRoles:
  default: opencode-go/minimax-m3:off
  plan: opencode-go/minimax-m3
  advisor: opencode-go/kimi-k2.7-code

# plan:
#   defaultOnStartup: true
#   enabled: true

advisor:
  enabled: true

task:
  disabledAgents: []
defaultThinkingLevel: auto
